### ISSUE TITLE
Sunset & redirect hilla.dev

### ISSUE THREAD

**Issue by rkalkowski** [vaadin/eslint-config-vaadin#67]
Please redirect hilla.dev to vaadin.com/hilla 

- To seamlessly redirect an old URL to a new one while preserving SEO rankings and traffic, implement a 301 permanent redirect

**Notes:**
When should we sunset [hilla.dev](http://hilla.dev/) and redirect it to [vaadin.com](http://vaadin.com/)? I just got a message on Twitter from someone who had run into issues trying to get started with Hilla on [hilla.dev](http://hilla.dev/), because the tutorials and guides linked from there are broken. Ping [@joonas](https://vaadin.slack.com/team/U04JAJGD6)

NEW

Joonas LehtinenJoonas Lehtinen

  [15 hours ago](https://vaadin.slack.com/archives/G04JKRY5J/p1718748495653719?thread_ts=1718709739.609619&cid=G04JKRY5J)

Sunset yes, but wouldn’t it be more appropriate to add a banner on site explaining and linking to our blog post on Vaadin.com?

NEW

Marcus HellbergMarcus Hellberg  [12 hours ago](https://vaadin.slack.com/archives/G04JKRY5J/p1718761683460309?thread_ts=1718709739.609619&cid=G04JKRY5J)

Sure. But we also need to get redirects in place for the front page, all the docs (and blog posts if we move them) for SEO so we don’t compete with ourselves. At that point there’s not a lot left

**Comment by web-padawan** [comment]
Thanks for the issue. Apparently you submitted it to the wrong repository though.
